trigger:
- main

stages:
- stage: Build
  displayName: Build .Net Solution
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
      fetchDepth: 0

    # Install the .NET 8 SDK
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.0.x'

    # Restore NuGet packages
    - task: DotNetCoreCLI@2
      displayName: 'Restore NuGet Packages'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    # Prepare SonarCloud analysis
    - task: SonarCloudPrepare@3
      inputs:
        scannerMode: 'dotnet'
        SonarCloud: 'SonarCloud'
        organization: 'vadsolodovnik'
        projectKey: 'vadsolodovnik_CoinsManagerAPI'
        projectName: 'CoinsManagerAPI'
        extraProperties: |
          sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/TestResults/coverage.opencover.xml

    # Build the solution
    - task: DotNetCoreCLI@2
      displayName: 'Build Solution'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration Release'

    # Clean Artifacts directory
    - script: |
        rm -rf $(Build.ArtifactStagingDirectory)/*
      displayName: 'Clean Artifact Staging Directory'

    # Publish the App Service artifacts
    - task: DotNetCoreCLI@2
      displayName: 'Publish App Service'
      inputs:
        command: 'publish'
        projects: '**/CoinsManagerService/CoinsManagerService.csproj'
        arguments: '-c Release -r linux-x64 --output $(Build.ArtifactStagingDirectory)/AppService'

    # Publish the Azure Function artifact (ensure it's isolated)
    - task: DotNetCoreCLI@2
      displayName: 'Publish Azure Function'
      inputs:
        command: 'publish'
        projects: '**/AzureFunctions/ProcessImagesFunction/ProcessImagesFunction.csproj'
        arguments: '-c Release --output $(Build.ArtifactStagingDirectory)/AzureFunctions/ProcessImagesFunction'

    - script: ls -R $(Build.ArtifactStagingDirectory)/AzureFunctions/ProcessImagesFunction
      displayName: 'List Published Azure Function Files'
    
    # Run Unit Tests with coverage
    - task: DotNetCoreCLI@2
      displayName: 'Run Unit Tests'
      inputs:
        command: 'test'
        projects: '**/*Tests/*.csproj'
        arguments: '/p:CollectCoverage=true /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/coverage.opencover.xml /p:CoverletOutputFormat=opencover'

    # Display coverage report
    - script: cat $(Build.SourcesDirectory)/TestResults/coverage.opencover.xml
      displayName: 'Display Coverage Report Contents'

    # Publish test results
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.SourcesDirectory)/TestResults'
        artifact: 'TestResults'
        publishLocation: 'pipeline'

    # Analyze with SonarCloud
    - task: SonarCloudAnalyze@3
      inputs:
        jdkversion: 'JAVA_HOME_17_X64'

    # Publish SonarCloud results
    - task: SonarCloudPublish@3
      inputs:
        pollingTimeoutSec: '300'

    # Publish App Service artifact
    - task: PublishBuildArtifacts@1
      displayName: 'Publish App Service Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/AppService'
        ArtifactName: 'AppService'
        publishLocation: 'Container'

    # Publish Azure Function artifact
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Azure Function Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/AzureFunctions/ProcessImagesFunction'
        ArtifactName: 'ProcessImagesFunction'
        publishLocation: 'Container'
